server:
  port: 80

spring:
  application:
    name: cloud-consumer-order

eureka:
  client:
    #表示是否讲自己注册进eureka。默认为true
    register-with-eureka: true
    #是否从eureka Server抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true，才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  #用于在eureka页面上显示ip地址和主机名修改。需pom中的spring-boot-starter-web和spring-boot-starter-actuator依赖
  instance:
    instance-id: order80  #主机名修改
    prefer-ip-address: true   #访问路径可以显示ip地址